version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9001:9001
    networks:
      - mynetwork
  jenkins:
    image: jenkins/jenkins:2.249.2-jdk11
    ports:
      - 8082:8082
    networks:
      - mynetwork
networks:
  mynetwork: